import { baseTemplate, footerNote } from './base.template';

export type OtpType = 'sign-in' | 'email-verification' | 'forget-password';

const OTP_COPY: Record<OtpType, { heading: string; subtext: string }> = {
  'sign-in': {
    heading: 'Sign-in verification code',
    subtext: 'Use the code below to complete your sign-in.',
  },
  'email-verification': {
    heading: 'Verify your email address',
    subtext: 'Use the code below to verify your Apio account.',
  },
  'forget-password': {
    heading: 'Password reset code',
    subtext: 'Use the code below to reset your password.',
  },
};

/**
 * OTP / verification code email.
 * @param otp   - 6-digit code generated by BetterAuth
 * @param type  - context: sign-in | email-verification | forget-password
 */
export function otpTemplate(otp: string, type: OtpType): string {
  const { heading, subtext } = OTP_COPY[type];

  const content = `
    <h2 style="margin:0 0 8px;font-size:24px;font-weight:800;color:#fff;letter-spacing:-0.5px;">
      ${heading}
    </h2>
    <p style="margin:0 0 28px;font-size:14px;color:#8b8ba7;line-height:1.7;">
      ${subtext}
    </p>

    <!-- OTP Box -->
    <div style="background:#0a0a12;border:1.5px solid #6366f1;border-radius:14px;
                padding:28px 20px;text-align:center;margin-bottom:24px;">
      <span style="font-size:42px;font-weight:900;letter-spacing:14px;
                   color:#6366f1;font-variant-numeric:tabular-nums;">
        ${otp}
      </span>
    </div>

    <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
      <span style="font-size:13px;color:#8b8ba7;">
        ⏱ This code expires in <strong style="color:#fff;">10 minutes</strong>.
      </span>
    </div>

    ${footerNote("If you didn't request this code, you can safely ignore this email. Someone may have typed your email address by mistake.")}
  `;

  return baseTemplate(content);
}
