/** Full source of ApiMonitorFilter.java — copied to user's Spring Boot project */
export const JAVA_FILTER_CODE = [
  '// Step 1: Add your package declaration as the very first line, e.g.:',
  '// package com.acme.backend;',
  '// Then copy this file into src/main/java/<your/package>/ApiMonitorFilter.java',
  '',
  'import jakarta.servlet.*; import jakarta.servlet.http.*;',
  'import org.springframework.beans.factory.annotation.Value;',
  'import org.springframework.stereotype.Component;',
  'import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets;',
  'import java.time.Instant; import java.util.*; import java.util.concurrent.*;',
  'import java.util.concurrent.atomic.AtomicBoolean;',
  '',
  '@Component',
  'public class ApiMonitorFilter implements Filter {',
  '',
  '    @Value("${APIO_SDK_TOKEN:}") private String sdkToken;',
  '    @Value("${APIO_BACKEND_URL:http://localhost:4000}") private String backendUrl;',
  '    private final BlockingQueue<Map<String, Object>> queue = new LinkedBlockingQueue<>(1000);',
  '    private final AtomicBoolean started = new AtomicBoolean(false);',
  '    private ScheduledExecutorService scheduler;',
  '',
  '    @Override public void init(FilterConfig c) { startSender(); }',
  '',
  '    @Override',
  '    public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain)',
  '            throws IOException, ServletException {',
  '        if (!(req instanceof HttpServletRequest h)) { chain.doFilter(req, res); return; }',
  '        long t = System.currentTimeMillis(); Instant st = Instant.now();',
  '        String q = h.getQueryString();',
  '        StatusCapture w = new StatusCapture((HttpServletResponse) res);',
  '        chain.doFilter(req, w);',
  '        Map<String, Object> e = new LinkedHashMap<>();',
  '        e.put("method", h.getMethod());',
  '        e.put("url", "http://" + h.getServerName() + ":" + h.getServerPort()',
  '              + h.getRequestURI() + (q != null ? "?" + q : ""));',
  '        e.put("statusCode", w.getCapturedStatus());',
  '        e.put("statusText", w.getCapturedStatus() >= 400 ? "error" : "success");',
  '        e.put("latency", System.currentTimeMillis() - t);',
  '        e.put("startedAt", st.toString()); e.put("endedAt", Instant.now().toString());',
  '        queue.offer(e);',
  '    }',
  '',
  '    private void startSender() {',
  '        if (!started.compareAndSet(false, true)) return;',
  '        if (sdkToken == null || sdkToken.isBlank()) {',
  '            System.out.println("[api-monitor] APIO_SDK_TOKEN not set — disabled"); return;',
  '        }',
  '        String url = backendUrl.stripTrailing() + "/api/v1/ingest";',
  '        System.out.println("[api-monitor] Sender active -> " + url);',
  '        scheduler = Executors.newSingleThreadScheduledExecutor(r -> {',
  '            Thread t2 = new Thread(r, "api-monitor-sender"); t2.setDaemon(true); return t2;',
  '        });',
  '        scheduler.scheduleAtFixedRate(() -> {',
  '            List<Map<String, Object>> batch = new ArrayList<>();',
  '            queue.drainTo(batch); if (batch.isEmpty()) return;',
  '            byte[] body = toJson(Map.of("sdkToken", sdkToken, "events", batch))',
  '                          .getBytes(StandardCharsets.UTF_8);',
  '            try {',
  '                HttpURLConnection c = (HttpURLConnection) URI.create(url).toURL().openConnection();',
  '                c.setRequestMethod("POST"); c.setDoOutput(true);',
  '                c.setConnectTimeout(3000); c.setReadTimeout(5000);',
  '                c.setRequestProperty("Content-Type", "application/json");',
  '                c.setRequestProperty("Content-Length", String.valueOf(body.length));',
  '                try (OutputStream os = c.getOutputStream()) { os.write(body); }',
  '                c.getResponseCode(); c.disconnect();',
  '            } catch (IOException ex) { batch.forEach(queue::offer); }',
  '        }, 500, 500, TimeUnit.MILLISECONDS);',
  '    }',
  '',
  '    private String toJson(Object o) {',
  '        if (o == null) return "null";',
  '        if (o instanceof String s)',
  '            return "\\"" + s.replace("\\\\","\\\\\\\\").replace("\\"","\\\\\\"").replace("\\n","\\\\n") + "\\"";',
  '        if (o instanceof Number || o instanceof Boolean) return o.toString();',
  '        if (o instanceof Map<?,?> m) {',
  '            var sb = new StringBuilder("{"); boolean f=true;',
  '            for (var en:m.entrySet()){if(!f)sb.append(",");',
  '                sb.append("\\"").append(en.getKey()).append("\\":").append(toJson(en.getValue()));f=false;}',
  '            return sb.append("}").toString();',
  '        }',
  '        if (o instanceof List<?> l) {',
  '            var sb = new StringBuilder("["); boolean f=true;',
  '            for (var i:l){if(!f)sb.append(",");sb.append(toJson(i));f=false;}',
  '            return sb.append("]").toString();',
  '        }',
  '        return "\\"" + o + "\\"";',
  '    }',
  '',
  '    static class StatusCapture extends HttpServletResponseWrapper {',
  '        private int status = 200;',
  '        StatusCapture(HttpServletResponse r) { super(r); }',
  '        @Override public void setStatus(int sc) { status=sc; super.setStatus(sc); }',
  '        @Override public void sendError(int sc) throws IOException { status=sc; super.sendError(sc); }',
  '        @Override public void sendError(int sc, String m) throws IOException { status=sc; super.sendError(sc,m); }',
  '        int getCapturedStatus() { return status; }',
  '    }',
  '}',
].join('\n');
